import { clockLabel } from './live-game-utils';
import type { LiveGameAlert, Player } from '@/types';
import { BellRing } from 'lucide-react';

export function AlertsPanel({ alerts, players }: { alerts: LiveGameAlert[]; players: Player[] }) {
    const typeLabels: Record<string, string> = { hot_player: 'Hot player', cold_player: 'Cold player', foul_trouble: 'Foul trouble', opponent_run: 'Opponent run', team_drought: 'Team drought', timeout_prompt: 'Timeout prompt', substitution_prompt: 'Substitution prompt' };
    const severityClasses: Record<string, string> = { info: 'bg-cyan-300/10 text-cyan-200', warning: 'bg-amber-300/10 text-amber-200' };

    return <section className="rounded-lg border border-border bg-card" aria-labelledby="alerts-heading"><div className="flex items-center justify-between border-b border-border px-4 py-3"><h2 id="alerts-heading" className="flex items-center gap-2 text-sm font-bold uppercase tracking-[0.1em] text-foreground"><BellRing size={16} className="text-amber-300" /> Coach alerts</h2><span className="text-xs text-muted-foreground">{alerts.length} active</span></div><div className="max-h-[240px] overflow-y-auto">{alerts.map((alert) => { const player = alert.player_id ? players.find((candidate) => candidate.id === alert.player_id) : undefined; return <div key={alert.id} className="border-b border-border/70 px-4 py-3 last:border-b-0"><div className="flex items-center justify-between gap-2"><p className="text-sm font-semibold text-foreground">{alert.message}</p><span className={`shrink-0 rounded px-2 py-0.5 text-xs font-bold uppercase ${severityClasses[alert.severity] ?? 'bg-muted text-muted-foreground'}`}>{alert.severity}</span></div><p className="mt-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground">{typeLabels[alert.type] ?? alert.type.replaceAll('_', ' ')} · Q{alert.period} {clockLabel(alert.clock_seconds_remaining)}{player ? ` · ${player.first_name} ${player.last_name}` : ''}</p></div>; })}{alerts.length === 0 && <p className="p-5 text-sm text-muted-foreground">No rule-based alerts are active.</p>}</div></section>;
}
