import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import type { LiveGame, PageProps } from '@/types';
import { Head, Link } from '@inertiajs/react';
import { ArrowRight, CalendarDays, CircleDot, Plus, Radio } from 'lucide-react';

interface LiveGamesIndexProps extends PageProps {
    liveGames: LiveGame[];
}

export default function LiveGamesIndex({ liveGames, flash }: LiveGamesIndexProps) {
    return <AuthenticatedLayout><Head title="Live Games" /><div className="mx-auto flex max-w-6xl flex-col gap-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-display text-xl font-black uppercase tracking-[0.12em] text-foreground">Live games</h1><p className="mt-1 text-sm text-muted-foreground">Set up a game, record courtside events, and follow the authoritative game state.</p></div><Link href={route('live-games.create')} className="flex h-10 items-center gap-2 rounded-md bg-amber-400 px-4 text-sm font-bold uppercase tracking-wide text-black transition-colors hover:bg-amber-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300"><Plus size={16} /> New live game</Link></div>{flash?.success && <p className="live-badge-info rounded-md px-4 py-3 text-sm font-semibold">{flash.success}</p>}<section className="overflow-hidden rounded-lg border border-border bg-card" aria-label="Live games list"><div className="grid grid-cols-[1fr_auto] border-b border-border px-4 py-3 text-xs font-bold uppercase tracking-[0.1em] text-muted-foreground sm:grid-cols-[1.5fr_1fr_1fr_auto]"><span>Matchup</span><span className="hidden sm:block">Status</span><span className="hidden sm:block">Clock</span><span className="text-right">Open</span></div>{liveGames.map((game) => <Link key={game.id} href={route('live-games.show', { liveGame: game.id })} className="grid min-h-[70px] grid-cols-[1fr_auto] items-center gap-3 border-b border-border/70 px-4 py-3 transition-colors last:border-b-0 hover:bg-muted/30 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-cyan-300 sm:grid-cols-[1.5fr_1fr_1fr_auto]"><div className="min-w-0"><p className="truncate font-semibold text-foreground">{game.home_team?.name ?? 'Home team'} <span className="text-muted-foreground">vs</span> {game.opponent_team?.name ?? 'Opponent'}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><CalendarDays size={13} /> {game.game_date ?? 'Unscheduled'}</p></div><StatusBadge status={game.status} /><span className="live-text-info hidden font-mono text-sm sm:block">Q{game.current_period} {String(Math.floor(game.clock_seconds_remaining / 60))}:{String(game.clock_seconds_remaining % 60).padStart(2, '0')}</span><ArrowRight size={18} className="justify-self-end text-muted-foreground" /></Link>)}{liveGames.length === 0 && <div className="flex min-h-[260px] flex-col items-center justify-center gap-3 px-4 text-center"><Radio size={28} className="live-text-warn" /><p className="font-semibold text-foreground">No live games have been set up.</p><Link href={route('live-games.create')} className="live-text-warn text-sm font-bold hover:opacity-80 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300">Set up a game</Link></div>}</section></div></AuthenticatedLayout>;
}

function StatusBadge({ status }: { status: LiveGame['status'] }) {
    const styles = status === 'live' ? 'live-badge-info' : status === 'finished' ? 'border border-border bg-muted/50 text-muted-foreground' : 'live-badge-warn';
    return <span className={`w-fit rounded px-2 py-1 text-xs font-bold uppercase tracking-wide ${styles}`}><CircleDot size={11} className="mr-1 inline" />{status}</span>;
}
